//
// Created by nikesh on 4/17/24.
//

#include "FilamentDiamSensor.h"

FilamentDiamSensor::FilamentDiamSensor(int pin, int pin2) {
    this->pin = pin;
    this->pin2 = pin2;
    pinMode(pin, INPUT);
    pinMode(pin2, INPUT);
}

void FilamentDiamSensor:setFilamentWindingSpeed(float speed){
    this->filamentWindingSpeed = speed;
};

//TODO: Implement the moving average function and the other one since this is autogenerated
float  FilamentDiamSensor::getDiameter(){
    float rawValue = getRawValue();
    float diameter = rawValue * calibartionFactor;
    return diameter;
}


String FilamentDiamSensor::getDiameterString(){
    float diameter = getDiameter();
    String diameterString = String(diameter);
    return diameterString;
}